# Institutional Portfolio & Risk Analytics Dashboard

# Notebook 1: 
Download Historical Stock Data

# Objective: 
Download historical stock price data using Python and prepare it for portfolio analysis.

# Author:
Ekta Lanjewar

# workflow

Import libraries
        ↓
Choose portfolio
        ↓
Download data
        ↓
Inspect dataset
        ↓
Check missing values
        ↓
Extract Adj Close
        ↓
Handle missing values
        ↓
Verify data quality

In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
tickers= [
    "AAPL",
    "MSFT",
    "NVDA",
    "ASML",
    "MC.PA",
    "SIE.DE",
    "BNP.PA",
    "NVO",
    "SHEL"
]
benchmark = "^GSPC" #S&P500
start_date = "2019-01-01"
end_date = "2025-12-31"
data= yf.download(tickers, start= start_date, end= end_date, auto_adjust= False)

data.head()

[*********************100%***********************]  9 of 9 completed

Price       Adj Close                                                          \
Ticker           AAPL        ASML     BNP.PA       MC.PA       MSFT      NVDA
Date
2019-01-02  37.469208  145.036728  25.002781  222.208694  94.193130  3.373052
2019-01-03  33.736988  137.037842  24.855648  213.743149  90.727951  3.169263
2019-01-04  35.177200  142.967438  26.061495  220.322617  94.947655  3.372309
2019-01-07  35.098896  146.233749  26.023106  219.927841  95.068756  3.550842
2019-01-08  35.768002  145.157349  26.154245  226.814270  95.758057  3.462442

Price                                            Close  ...       Open  \
Ticker            NVO       SHEL     SIE.DE       AAPL  ...     SIE.DE
Date                                                    ...
2019-01-02  19.790527  43.267853  69.748085  39.480000  ...  87.459618
2019-01-03  19.951252  43.173058  67.877800  35.547501  ...  87.684982
2019-01-04  20.023155  44.150116  70.537437  37.064999  ...  86.936768
2019-01-07  20.150049  44.208447  69.612953  36.982498  ...  90.055817
2019-01-08  20.446119  43.938667  69.890305  37.687500  ...  88.189796

Price            Volume                                              \
Ticker             AAPL       ASML     BNP.PA     MC.PA        MSFT
Date
2019-01-02  148158800.0   602500.0  4275030.0  561858.0  35329300.0
2019-01-03  365248800.0  1078600.0  4011198.0  785119.0  42579100.0
2019-01-04  234428400.0   589500.0  5325079.0  886586.0  44060600.0
2019-01-07  219111200.0   971900.0  4195675.0  550835.0  35656100.0
2019-01-08  164101200.0   531700.0  4372775.0  742574.0  31514400.0

Price
Ticker             NVDA        NVO       SHEL     SIE.DE
Date
2019-01-02  508752000.0  2595800.0  3918326.0  2435666.0
2019-01-03  705552000.0  3092800.0  3523203.0  2865101.0
2019-01-04  585620000.0  3838400.0  4106479.0  3020567.0
2019-01-07  709160000.0  5054800.0  3678599.0  2798903.0
2019-01-08  786016000.0  4097400.0  3134058.0  2697618.0

[5 rows x 54 columns]

# Check object type
type(data)

# Check dataset dimensions
data.shape

# View column names
data.columns

# View row index (dates)
data.index

# Summarize dataset
data.info()

# Count missing values
data.isna().sum()

In [8]:
data.shape

(1809, 54)

1. 1809 → the number of rows (one row per trading day).
2. For each stock, Yahoo Finance returned multiple fields:
Open
High
Low
Close
Adj Close
Volume

Since you downloaded 9 stocks, there are:

6 fields × 9 stocks = 54 columns

In [11]:
data.columns

MultiIndex([('Adj Close',   'AAPL'),
            ('Adj Close',   'ASML'),
            ('Adj Close', 'BNP.PA'),
            ('Adj Close',  'MC.PA'),
            ('Adj Close',   'MSFT'),
            ('Adj Close',   'NVDA'),
            ('Adj Close',    'NVO'),
            ('Adj Close',   'SHEL'),
            ('Adj Close', 'SIE.DE'),
            (    'Close',   'AAPL'),
            (    'Close',   'ASML'),
            (    'Close', 'BNP.PA'),
            (    'Close',  'MC.PA'),
            (    'Close',   'MSFT'),
            (    'Close',   'NVDA'),
            (    'Close',    'NVO'),
            (    'Close',   'SHEL'),
            (    'Close', 'SIE.DE'),
            (     'High',   'AAPL'),
            (     'High',   'ASML'),
            (     'High', 'BNP.PA'),
            (     'High',  'MC.PA'),
            (     'High',   'MSFT'),
            (     'High',   'NVDA'),
            (     'High',    'NVO'),
            (     'High',   'SHEL'),
            (     'High', 'SIE.DE'),
            (      'Low',   'AAPL'),
            (      'Low',   'ASML'),
            (      'Low', 'BNP.PA'),
            (      'Low',  'MC.PA'),
            (      'Low',   'MSFT'),
            (      'Low',   'NVDA'),
            (      'Low',    'NVO'),
            (      'Low',   'SHEL'),
            (      'Low', 'SIE.DE'),
            (     'Open',   'AAPL'),
            (     'Open',   'ASML'),
            (     'Open', 'BNP.PA'),
            (     'Open',  'MC.PA'),
            (     'Open',   'MSFT'),
            (     'Open',   'NVDA'),
            (     'Open',    'NVO'),
            (     'Open',   'SHEL'),
            (     'Open', 'SIE.DE'),
            (   'Volume',   'AAPL'),
            (   'Volume',   'ASML'),
            (   'Volume', 'BNP.PA'),
            (   'Volume',  'MC.PA'),
            (   'Volume',   'MSFT'),
            (   'Volume',   'NVDA'),
            (   'Volume',    'NVO'),
            (   'Volume',   'SHEL'),
            (   'Volume', 'SIE.DE')],
           names=['Price', 'Ticker'])

In [14]:
type(data)

pandas.core.frame.DataFrame

In [17]:
data.index #This tells us the index contains dates and times. "Every row in this DataFrame is identified by a date.

DatetimeIndex(['2019-01-02', '2019-01-03', '2019-01-04', '2019-01-07',
               '2019-01-08', '2019-01-09', '2019-01-10', '2019-01-11',
               '2019-01-14', '2019-01-15',
               ...
               '2025-12-16', '2025-12-17', '2025-12-18', '2025-12-19',
               '2025-12-22', '2025-12-23', '2025-12-24', '2025-12-26',
               '2025-12-29', '2025-12-30'],
              dtype='datetime64[ns]', name='Date', length=1809, freq=None)

## Data Inspection (data.info)

In this section, we inspect the downloaded dataset to understand:

- its structure,
- data types,
- missing values (NaN),
- and overall quality before performing any analysis.

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1809 entries, 2019-01-02 to 2025-12-30
Data columns (total 54 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   (Adj Close, AAPL)    1759 non-null   float64
 1   (Adj Close, ASML)    1759 non-null   float64
 2   (Adj Close, BNP.PA)  1793 non-null   float64
 3   (Adj Close, MC.PA)   1793 non-null   float64
 4   (Adj Close, MSFT)    1759 non-null   float64
 5   (Adj Close, NVDA)    1759 non-null   float64
 6   (Adj Close, NVO)     1759 non-null   float64
 7   (Adj Close, SHEL)    1759 non-null   float64
 8   (Adj Close, SIE.DE)  1779 non-null   float64
 9   (Close, AAPL)        1759 non-null   float64
 10  (Close, ASML)        1759 non-null   float64
 11  (Close, BNP.PA)      1793 non-null   float64
 12  (Close, MC.PA)       1793 non-null   float64
 13  (Close, MSFT)        1759 non-null   float64
 14  (Close, NVDA)        1759 non-null   float64
 15  (Close, NVO)         1759 non-null   float64
 16  (Close, SHEL)        1759 non-null   float64
 17  (Close, SIE.DE)      1779 non-null   float64
 18  (High, AAPL)         1759 non-null   float64
 19  (High, ASML)         1759 non-null   float64
 20  (High, BNP.PA)       1793 non-null   float64
 21  (High, MC.PA)        1793 non-null   float64
 22  (High, MSFT)         1759 non-null   float64
 23  (High, NVDA)         1759 non-null   float64
 24  (High, NVO)          1759 non-null   float64
 25  (High, SHEL)         1759 non-null   float64
 26  (High, SIE.DE)       1779 non-null   float64
 27  (Low, AAPL)          1759 non-null   float64
 28  (Low, ASML)          1759 non-null   float64
 29  (Low, BNP.PA)        1793 non-null   float64
 30  (Low, MC.PA)         1793 non-null   float64
 31  (Low, MSFT)          1759 non-null   float64
 32  (Low, NVDA)          1759 non-null   float64
 33  (Low, NVO)           1759 non-null   float64
 34  (Low, SHEL)          1759 non-null   float64
 35  (Low, SIE.DE)        1779 non-null   float64
 36  (Open, AAPL)         1759 non-null   float64
 37  (Open, ASML)         1759 non-null   float64
 38  (Open, BNP.PA)       1793 non-null   float64
 39  (Open, MC.PA)        1793 non-null   float64
 40  (Open, MSFT)         1759 non-null   float64
 41  (Open, NVDA)         1759 non-null   float64
 42  (Open, NVO)          1759 non-null   float64
 43  (Open, SHEL)         1759 non-null   float64
 44  (Open, SIE.DE)       1779 non-null   float64
 45  (Volume, AAPL)       1759 non-null   float64
 46  (Volume, ASML)       1759 non-null   float64
 47  (Volume, BNP.PA)     1793 non-null   float64
 48  (Volume, MC.PA)      1793 non-null   float64
 49  (Volume, MSFT)       1759 non-null   float64
 50  (Volume, NVDA)       1759 non-null   float64
 51  (Volume, NVO)        1759 non-null   float64
 52  (Volume, SHEL)       1759 non-null   float64
 53  (Volume, SIE.DE)     1779 non-null   float64
dtypes: float64(54)
memory usage: 777.3 KB

## Missing Values

Since the portfolio contains stocks listed on different exchanges (US, France, Germany, Denmark, UK), different market holidays may result in missing observations. We inspect these missing values before deciding on a cleaning strategy.

# Check for missing (NaN) values in each column.
# isna() identifies missing values, and sum() counts them.
# This helps assess data quality before analysis.

In [21]:
data.isna().sum()

Price      Ticker
Adj Close  AAPL      50
           ASML      50
           BNP.PA    16
           MC.PA     16
           MSFT      50
           NVDA      50
           NVO       50
           SHEL      50
           SIE.DE    30
Close      AAPL      50
           ASML      50
           BNP.PA    16
           MC.PA     16
           MSFT      50
           NVDA      50
           NVO       50
           SHEL      50
           SIE.DE    30
High       AAPL      50
           ASML      50
           BNP.PA    16
           MC.PA     16
           MSFT      50
           NVDA      50
           NVO       50
           SHEL      50
           SIE.DE    30
Low        AAPL      50
           ASML      50
           BNP.PA    16
           MC.PA     16
           MSFT      50
           NVDA      50
           NVO       50
           SHEL      50
           SIE.DE    30
Open       AAPL      50
           ASML      50
           BNP.PA    16
           MC.PA     16
           MSFT      50
           NVDA      50
           NVO       50
           SHEL      50
           SIE.DE    30
Volume     AAPL      50
           ASML      50
           BNP.PA    16
           MC.PA     16
           MSFT      50
           NVDA      50
           NVO       50
           SHEL      50
           SIE.DE    30
dtype: int64

## Select Adjusted Closing Prices

Portfolio returns should be calculated using Adjusted Closing Prices because they account for stock splits and dividend adjustments.

In [25]:
adj_close= data['Adj Close']
adj_close

Ticker,AAPL,ASML,BNP.PA,MC.PA,MSFT,NVDA,NVO,SHEL,SIE.DE
Date,,,,,,,,,
2019-01-02,37.469208,145.036728,25.002781,222.208694,94.193130,3.373052,19.790527,43.267853,69.748085
2019-01-03,33.736988,137.037842,24.855648,213.743149,90.727951,3.169263,19.951252,43.173058,67.877800
2019-01-04,35.177200,142.967438,26.061495,220.322617,94.947655,3.372309,20.023155,44.150116,70.537437
2019-01-07,35.098896,146.233749,26.023106,219.927841,95.068756,3.550842,20.150049,44.208447,69.612953
2019-01-08,35.768002,145.157349,26.154245,226.814270,95.758057,3.462442,20.446119,43.938667,69.890305
...,...,...,...,...,...,...,...,...,...
2025-12-23,271.854919,1056.763306,78.288795,617.235291,484.691528,188.979507,49.784172,71.743095,232.849701
2025-12-24,273.302216,1060.425903,78.201378,621.958252,485.856323,188.380234,50.700565,71.517265,NaN
2025-12-26,272.892975,1067.621216,NaN,NaN,485.547699,190.297897,50.546227,71.487808,NaN
2025-12-29,273.252350,1060.903564,77.910027,623.040649,484.940430,187.990707,49.649128,71.792191,232.115311
2025-12-30,272.573578,1067.014282,78.764679,629.042725,485.318726,187.311539,49.407970,72.489296,234.171585

## Handle Missing Values

The portfolio contains stocks listed on different exchanges, which observe different trading holidays. As a result, some dates contain missing (`NaN`) prices.

Using `dropna()` would remove every row containing at least one missing value, causing unnecessary loss of valid market data.

Instead, `ffill()` (forward fill) replaces each missing value with the most recent available price, preserving the time series for portfolio analysis.

### Example

Before:

| Date | Siemens |
|------|---------|
| 23 Dec | 230 |
| 24 Dec | NaN |
| 25 Dec | NaN |
| 26 Dec | 235 |

After `ffill()`:

| Date | Siemens |
|------|---------|
| 23 Dec | 230 |
| 24 Dec | 230 |
| 25 Dec | 230 |
| 26 Dec | 235 |

In [30]:
adj_close= adj_close.ffill()
adj_close.head() #Printing all 1,809 rows clutters the notebook. Usually we inspect only the beginning or end of the dataset.

Ticker,AAPL,ASML,BNP.PA,MC.PA,MSFT,NVDA,NVO,SHEL,SIE.DE
Date,,,,,,,,,
2019-01-02,37.469208,145.036728,25.002781,222.208694,94.193130,3.373052,19.790527,43.267853,69.748085
2019-01-03,33.736988,137.037842,24.855648,213.743149,90.727951,3.169263,19.951252,43.173058,67.877800
2019-01-04,35.177200,142.967438,26.061495,220.322617,94.947655,3.372309,20.023155,44.150116,70.537437
2019-01-07,35.098896,146.233749,26.023106,219.927841,95.068756,3.550842,20.150049,44.208447,69.612953
2019-01-08,35.768002,145.157349,26.154245,226.814270,95.758057,3.462442,20.446119,43.938667,69.890305

In [31]:
adj_close.isna().sum()

Ticker
AAPL      0
ASML      0
BNP.PA    0
MC.PA     0
MSFT      0
NVDA      0
NVO       0
SHEL      0
SIE.DE    0
dtype: int64

# how to save as csv
1. ..      = Go back one folder
2. /data   = Enter the data folder
3. adj_close.csv = Save the file with this name

In [41]:
adj_close.to_csv("../data/adj_close.csv")

In [42]:
import os

os.listdir("../data")

['adj_close.csv']